CREATE DATABASE ACTIVIDAD_1_1_20241C
GO
USE ACTIVIDAD_1_1_20241C
GO
CREATE TABLE CURSOS(
    ID_CURSO INT NOT NULL PRIMARY KEY,
    NOMBRE_CURSO VARCHAR(50) NOT NULL,
    FECHA_ESTRENO DATE NOT NULL,
    COSTO_CURSADO MONEY NOT NULL,
    COSTO_CERTIFICACION MONEY NOT NULL,
    NIVEL INT NULL,
)
GO
CREATE TABLE CLASES(
    ID_CLASE INT NOT NULL PRIMARY KEY,
    ID_CURSO INT NOT NULL FOREIGN KEY REFERENCES CURSOS(ID_CURSO),
    NOMBRE VARCHAR(50) NOT NULL,
    NUMERO INT NOT NULL,
    DURACION INT NOT NULL, 
)
GO
CREATE TABLE TIPOS_CONTENIDO(
    ID_TIPO INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL, 
)
GO
CREATE TABLE CONTENIDO(
    ID_CONTENIDO INT NOT NULL PRIMARY KEY,
    ID_CLASE INT NOT NULL FOREIGN KEY REFERENCES CLASES(ID_CLASE),
    NOMBRE VARCHAR(50) NOT NULL,
    ID_TIPO INT NOT NULL FOREIGN KEY REFERENCES TIPOS_CONTENIDO(ID_TIPO),
    TAMANIO BIGINT NOT NULL, 
)
GO
CREATE TABLE TIPOS_IDIOMA(
    ID_TIPO INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL, 
)
GO
CREATE TABLE IDIOMA(
    ID_IDIOMA INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL, 
    ID_TIPO INT NOT NULL FOREIGN KEY REFERENCES TIPOS_IDIOMA(ID_TIPO),
)
GO
CREATE TABLE CURSO_X_IDIOMA(
    ID_CURSO INT NOT NULL FOREIGN KEY REFERENCES CURSOS(ID_CURSO),
    ID_IDIOMA INT NOT NULL FOREIGN KEY REFERENCES IDIOMA(ID_IDIOMA),
    PRIMARY KEY (ID_CURSO, ID_IDIOMA),
)
GO
CREATE TABLE CATEGORIAS(
    ID_CATEGORIA INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL, 
)
GO
CREATE TABLE CURSO_X_CATEGORIA(
    ID_CURSO INT NOT NULL FOREIGN KEY REFERENCES CURSOS(ID_CURSO),
    ID_CATEGORIA INT NOT NULL FOREIGN KEY REFERENCES CATEGORIAS(ID_CATEGORIA),
    PRIMARY KEY (ID_CURSO, ID_CATEGORIA),
)

USE ACTIVIDAD_1_1_20241C
GO
ALTER TABLE IDIOMA 
ADD TIPO VARCHAR(50) NOT NULL